services:
  - type: web
    name: baekilha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
