services:
  - type: web
    name: baekilha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: GROQ_API_KEY
        value: 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
