services:
  - type: web
    name: osbasic-backend
    env: python
    rootDir: . 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///performance.db
    plan: free
